# Site settings
title: "FontAwesome DataBase"
shortTitle: "FADB"
email: "dereknutile@gmail.com"
description: "Filterable database of FontAwesome icons."
tagline: "Find your FontAwesome font easily."
baseurl: ""
url: "http://fadb.us/"
fontAwesomeFontBaseUrl: "http://fortawesome.github.io/Font-Awesome/icon/"

# Build settings
markdown: kramdown
permalink: pretty
paginate_path: /page:num
timezone: null

repo: "https://github.com/fadbus/fadbus.github.io"
gacode: "UA-placeholder-1"
