# Site settings
title: "FontAwesome Metabase"
email: "dereknutile@gmail.com"
description: "Filterable database of <a href="http://fortawesome.github.io/Font-Awesome/" target="_blank">FontAwesome</a> icons."
tagline: "Find your FontAwesome font easily."
baseurl: "/"
url: "http://fadb.us/"

# Build settings
markdown: kramdown
permalink: pretty

gacode: "UA-53524614-1"
